include makefile.def
-include nofile.def1
sinclude nofile.def2
#include makefile.config

OBJS = main.o a.o b.o c.o

all:main

.PHONY: all

main: $(OBJS)
	g++ -o main $(OBJS)

#$(OBJS):%.o:%.cpp
%.o:%.cpp
	g++ -c $< -o $@

.PHONY: clean
clean:
	rm -rf $(OBJS) main
